name: CI

on:
  push:
    branches: [ "main" ]          # lance les tests après chaque push sur main
  pull_request:
    branches: [ "main" ]          # et sur chaque PR vers main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run Django tests
        env:
          DJANGO_SECRET_KEY: "ci-secret"
          DJANGO_DEBUG: "0"
          CORS_ALLOWED_ORIGINS: "http://localhost:5173"
        run: python manage.py test -v 2